# Python Fundamentals
## Introduction to Specialization

Teacher: Christopher Brooks

* Why python?
  * Full featured
  * SciPy ecosystem

Course outline
1. Python knowledge
2. Pandas toolkit (functionality seen in R, into python)
3. Advanced querying and manipulating data frames in pandas
4. Basic statistical analysis with numpy and scipy

## Intro to data science
6 Activities of data science:
1. Data exploration and preparation
2. Data representation and transformation
3. Computing with Data
4. Data Modeling
5. Data visualization and presentation
6. Science about Data science



In [3]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


In [4]:
def add_numbers(x, y, z=None, flag=False):
    if (flag):
        print('Flag is true!')
    if (z==None):
        return x + y
    else:
        return x + y + z
    
print(add_numbers(1, 2, flag=True))

Flag is true!
3


In [9]:
print(type('This is a string'))
print(type(None))
print(type(1))
print(type(1.0))
print(type(add_numbers))

<class 'str'>
<class 'NoneType'>
<class 'int'>
<class 'float'>
<class 'function'>


In [27]:
x = (1, 'a', 2, 'b')
print(type(x))
for item in x:
    print(item)
print("###")
for i in range(0,4):
    print(x[i])

<class 'tuple'>
1
a
2
b
###
1
a
2
b


In [11]:
x = [1, 'a', 2, 'b']
type(x)

list

In [12]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


In [13]:
[1,2] + [3,4]

[1, 2, 3, 4]

In [28]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x
print(lname)

Brooks


In [31]:
print('Alex'+ str(2))

Alex2


In [35]:
import numpy as np
r = np.arange(36)
r.resize((6, 6))
print(r)

r2 = r[:3,:3]
print(r2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]


In [36]:
r2[:] = 0
print(r)

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [37]:
r3 = r[5,5]
r3 = 100
print(r)

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
